"""x-s-common signature generation"""

import json
from typing import Any

from ..config import CryptoConfig
from ..core.crc32_encrypt import CRC32
from ..generators.fingerprint import FingerprintGenerator
from ..utils.encoder import Base64Encoder

__all__ = ["XsCommonSigner"]


class XsCommonSigner:
    """Generate x-s-common signatures"""

    def __init__(self, config: CryptoConfig | None = None):
        self.config = config or CryptoConfig()
        self._fp_generator = FingerprintGenerator(self.config)
        self._encoder = Base64Encoder(self.config)

    def sign(
        self,
        cookie_dict: dict[str, Any],
        *,
        fingerprint: dict[str, Any] | None = None,
        b1: str | None = None,
        dsllt: str | None = None,
        tiga: str | None = None,
    ) -> str:
        """Generate an x-s-common value for the current web protocol.

        ``x-s-common`` is not a cookie-only signature.  The web client embeds
        a browser fingerprint (``x8``) and, on newer builds, its security
        runtime state (``x12``).  A generated fingerprint is therefore a
        best-effort headless value; to reproduce a browser request, pass the
        fingerprint captured/generated by that same browser session.

        Args:
            cookie_dict: Parsed cookies. Must contain ``a1``.
            fingerprint: Optional web fingerprint. When supplied, its ``x33``
                ... ``x82`` fields are encrypted exactly as the web client.
            b1: Pre-computed ``b1`` fingerprint string (from browser
                ``localStorage``).  Takes priority over *fingerprint*.
            dsllt: Optional ``dsllt`` runtime value (from browser
                ``localStorage`` key ``dsllt``).
            tiga: Optional ``tiga`` runtime value (from browser
                ``localStorage`` key ``last_tiga_update_time``).
        """
        a1_value = cookie_dict["a1"]
        if b1 is None:
            if fingerprint is None:
                fingerprint = self._fp_generator.generate(
                    cookies=cookie_dict,
                    user_agent=self.config.PUBLIC_USERAGENT,
                )
            b1 = self._fp_generator.generate_b1(fingerprint)

        sign_struct = dict(self.config.SIGNATURE_XSCOMMON_TEMPLATE)
        sign_struct["x5"] = a1_value
        sign_struct["x8"] = b1
        sign_struct["x9"] = CRC32.crc32_js_int(b1)
        if dsllt is not None or tiga is not None:
            parts = [dsllt or "", tiga or ""]
            sign_struct["x12"] = ";".join(parts)

        sign_json = json.dumps(sign_struct, separators=(",", ":"), ensure_ascii=False)
        return self._encoder.encode(sign_json)
